In [1]:
import numpy as np

In [2]:
def preprocess(X):
    n = X.shape[0]
    return np.c_[np.ones(n), X]

data_train = np.genfromtxt("hw3_train.dat")
X_train = data_train[:, :-1]
y_train = data_train[:, -1].reshape(-1, 1)
X_train = preprocess(X_train)
data_test = np.genfromtxt("hw3_test.dat")
X_test = data_test[:, :-1]
y_test = data_test[:, -1].reshape(-1, 1)
X_test = preprocess(X_test)
print (X_train)

[[ 1.        2.965153  2.447427 ...  1.621895 -4.510862 -0.006392]
 [ 1.       -4.303194 -0.032933 ... -4.560341 -0.949456 -0.744622]
 [ 1.       -0.261568  0.974854 ... -4.031803  2.728657  4.001672]
 ...
 [ 1.       -3.106073 -0.425107 ... -2.093555 -1.741274  1.479998]
 [ 1.        3.665836  3.401544 ...  0.78021   2.058829  1.474205]
 [ 1.        1.74612   2.365236 ... -0.833364  3.269879 -0.259019]]


In [3]:
# problem 14
W_LIN = np.dot(np.dot(np.linalg.inv(np.dot(X_train.transpose(), X_train)), X_train.transpose()), y_train)
print (W_LIN)

E_in = 0

for i in range (1000):
    E_in += (1/1000)*(np.dot(X_train[i], W_LIN) - y_train[i])**2
    
print ('E_in =', E_in[0])

[[ 0.00754448]
 [ 0.14325775]
 [ 0.03548979]
 [ 0.02775754]
 [ 0.02547401]
 [-0.08173504]
 [ 0.0807915 ]
 [-0.10929449]
 [ 0.07789522]
 [ 0.16407524]
 [ 0.14069183]]
E_in = 0.6053223804672915


In [4]:
# problem 15

count_ave = 0

for j in range(1000):
    
    wt = np.zeros(11)
    E_wt = 0
    count = 0

    for i in range(1000):
        E_wt += (1/1000)*(np.dot(X_train[i], wt) - y_train[i])**2
    
    while E_wt > 1.01*E_in:
        E_wt = 0
        k = np.random.randint(1000)
        wt = wt + 0.001*2*(y_train[k] - np.dot(wt, X_train[k]))*X_train[k]
        count += 1
        for i in range (1000):
            E_wt += (1/1000)*(np.dot(X_train[i], wt) - y_train[i])**2
            
    count_ave += count

count_ave = count_ave / 1000
        
print (count_ave)

1857.858
